const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, VerticalAlign, PageBreak, LevelFormat,
  TabStopType, TabStopPosition, UnderlineType, SimpleField
} = require('docx');
const fs = require('fs');

// ─── Color palette ───────────────────────────────────────────────
const C = {
  navy:    "1B3A6B",
  blue:    "2563EB",
  teal:    "0F766E",
  steel:   "334155",
  silver:  "CBD5E1",
  snow:    "F0F4F8",
  white:   "FFFFFF",
  accent:  "EFF6FF",
  green:   "065F46",
  greenBg: "D1FAE5",
  orange:  "92400E",
  orangeBg:"FEF3C7",
  red:     "991B1B",
  redBg:   "FEE2E2",
};

const border1 = { style: BorderStyle.SINGLE, size: 4, color: C.silver };
const borderNone = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };

// ─── Helpers ─────────────────────────────────────────────────────
function h1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 360, after: 160 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: C.navy, space: 6 } },
    children: [new TextRun({ text, font: "Arial", size: 32, bold: true, color: C.navy })]
  });
}
function h2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 280, after: 120 },
    children: [new TextRun({ text, font: "Arial", size: 26, bold: true, color: C.blue })]
  });
}
function h3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 200, after: 80 },
    children: [new TextRun({ text, font: "Arial", size: 22, bold: true, color: C.teal })]
  });
}
function p(text, opts = {}) {
  return new Paragraph({
    spacing: { before: 60, after: 100 },
    children: [new TextRun({ text, font: "Arial", size: 22, color: C.steel, ...opts })]
  });
}
function pBold(text) { return p(text, { bold: true }); }
function gap(n = 1) {
  return Array.from({ length: n }, () => new Paragraph({
    spacing: { before: 0, after: 0 },
    children: [new TextRun({ text: "", size: 20 })]
  }));
}
function bullet(text, level = 0) {
  return new Paragraph({
    numbering: { reference: "bullets", level },
    spacing: { before: 40, after: 60 },
    children: [new TextRun({ text, font: "Arial", size: 22, color: C.steel })]
  });
}
function numbered(text, level = 0) {
  return new Paragraph({
    numbering: { reference: "numbers", level },
    spacing: { before: 40, after: 60 },
    children: [new TextRun({ text, font: "Arial", size: 22, color: C.steel })]
  });
}
function code(text) {
  return new Paragraph({
    spacing: { before: 80, after: 80 },
    indent: { left: 720 },
    shading: { fill: "1E293B", type: ShadingType.CLEAR },
    children: [new TextRun({ text, font: "Courier New", size: 18, color: "E2E8F0" })]
  });
}
function infoBox(title, lines, fill = C.accent, titleColor = C.blue) {
  const rows = [
    new TableRow({
      children: [new TableCell({
        shading: { fill, type: ShadingType.CLEAR },
        margins: { top: 120, bottom: 80, left: 200, right: 200 },
        borders: { top: border1, bottom: border1, left: border1, right: border1 },
        children: [
          new Paragraph({ children: [new TextRun({ text: title, font: "Arial", size: 20, bold: true, color: titleColor })] }),
          ...lines.map(l => new Paragraph({ spacing: { before: 40, after: 40 }, children: [new TextRun({ text: l, font: "Arial", size: 20, color: C.steel })] }))
        ]
      })]
    })
  ];
  return new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: [9360], rows });
}
function twoColRow(label, value, shade = false) {
  const fill = shade ? "F1F5F9" : C.white;
  return new TableRow({
    children: [
      new TableCell({
        shading: { fill, type: ShadingType.CLEAR },
        margins: { top: 80, bottom: 80, left: 120, right: 120 },
        width: { size: 3120, type: WidthType.DXA },
        borders: { top: border1, bottom: border1, left: border1, right: border1 },
        children: [new Paragraph({ children: [new TextRun({ text: label, font: "Arial", size: 20, bold: true, color: C.navy })] })]
      }),
      new TableCell({
        shading: { fill, type: ShadingType.CLEAR },
        margins: { top: 80, bottom: 80, left: 120, right: 120 },
        width: { size: 6240, type: WidthType.DXA },
        borders: { top: border1, bottom: border1, left: border1, right: border1 },
        children: [new Paragraph({ children: [new TextRun({ text: value, font: "Arial", size: 20, color: C.steel })] })]
      }),
    ]
  });
}
function tableHeaderRow(cols, widths) {
  return new TableRow({
    tableHeader: true,
    children: cols.map((col, i) => new TableCell({
      shading: { fill: C.navy, type: ShadingType.CLEAR },
      margins: { top: 80, bottom: 80, left: 120, right: 120 },
      width: { size: widths[i], type: WidthType.DXA },
      borders: { top: border1, bottom: border1, left: border1, right: border1 },
      children: [new Paragraph({ children: [new TextRun({ text: col, font: "Arial", size: 20, bold: true, color: C.white })] })]
    }))
  });
}
function tableDataRow(cells, widths, shade = false) {
  const fill = shade ? "F8FAFC" : C.white;
  return new TableRow({
    children: cells.map((cell, i) => new TableCell({
      shading: { fill, type: ShadingType.CLEAR },
      margins: { top: 80, bottom: 80, left: 120, right: 120 },
      width: { size: widths[i], type: WidthType.DXA },
      borders: { top: border1, bottom: border1, left: border1, right: border1 },
      children: [new Paragraph({ children: [new TextRun({ text: cell, font: "Arial", size: 20, color: C.steel })] })]
    }))
  });
}

// ─── DOCUMENT BODY ───────────────────────────────────────────────
const children = [

  // ═══ COVER ═══
  ...gap(3),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 0, after: 60 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 12, color: C.navy, space: 4 } },
    children: [new TextRun({ text: "EXPLAINABLE MACHINE LEARNING FRAMEWORK", font: "Arial", size: 40, bold: true, color: C.navy })]
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 80, after: 80 },
    children: [new TextRun({ text: "FOR RAILWAY PREDICTIVE MAINTENANCE", font: "Arial", size: 36, bold: true, color: C.blue })]
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 40, after: 40 },
    children: [new TextRun({ text: "Using Data Streams from Metro Operator of Portugal", font: "Arial", size: 28, italic: true, color: C.teal })]
  }),
  ...gap(2),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 40, after: 40 },
    children: [new TextRun({ text: "COMPLETE PROJECT TUTORIAL & MANUAL GUIDE", font: "Arial", size: 24, bold: true, color: C.steel })]
  }),
  ...gap(1),
  new Paragraph({ children: [new TextRun({ text: "", size: 1 })], border: { top: { style: BorderStyle.SINGLE, size: 6, color: C.navy } } }),
  ...gap(1),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: "Field-Based Project | Department of Computer Science & Engineering", font: "Arial", size: 20, color: C.steel })]
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: "Version 1.0  |  2025", font: "Arial", size: 20, color: C.steel })]
  }),
  ...gap(2),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ TABLE OF CONTENTS ═══
  h1("Table of Contents"),
  ...[
    ["1.", "Project Overview & Objectives", "3"],
    ["2.", "Dataset Description — MetroPT-3", "4"],
    ["3.", "System Architecture & Pipeline", "5"],
    ["4.", "Environment Setup & Prerequisites", "6"],
    ["5.", "Data Acquisition & Preprocessing", "8"],
    ["6.", "Exploratory Data Analysis (EDA)", "11"],
    ["7.", "Feature Engineering", "13"],
    ["8.", "Machine Learning Models", "15"],
    ["9.", "Explainability with SHAP & LIME", "19"],
    ["10.", "Model Evaluation & Metrics", "22"],
    ["11.", "Real-Time Data Stream Processing", "24"],
    ["12.", "Dashboard & Visualization", "26"],
    ["13.", "Deployment Guide", "28"],
    ["14.", "Testing & Validation", "30"],
    ["15.", "Troubleshooting & FAQs", "32"],
    ["16.", "References & Resources", "33"],
  ].map(([num, title, pg]) =>
    new Paragraph({
      spacing: { before: 60, after: 60 },
      tabStops: [{ type: TabStopType.RIGHT, position: 9000, leader: TabStopType.DOT }],
      children: [
        new TextRun({ text: `${num}  ${title}`, font: "Arial", size: 22, color: C.navy }),
        new TextRun({ text: `\t${pg}`, font: "Arial", size: 22, color: C.steel }),
      ]
    })
  ),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 1 — OVERVIEW ═══
  h1("1. Project Overview & Objectives"),
  p("This field-based project builds an Explainable Machine Learning (XML) framework for predictive maintenance of railway systems using real sensor telemetry from Metro Operator of Portugal (MetroPT). The system detects failures in compressor air production units (APU) before they occur, reducing downtime and maintenance costs."),
  ...gap(1),
  h2("1.1 Problem Statement"),
  p("Unplanned failures in metro rail systems cost millions annually and risk passenger safety. Traditional rule-based monitoring triggers alerts only after faults occur. This project shifts to proactive, data-driven maintenance using streaming sensor data — and crucially, makes ML predictions interpretable to maintenance engineers."),
  ...gap(1),
  h2("1.2 Project Objectives"),
  bullet("Ingest and preprocess real-time sensor data streams from APU systems"),
  bullet("Build binary classifiers to predict compressor failures 15–30 minutes ahead"),
  bullet("Apply SHAP (SHapley Additive exPlanations) and LIME for model explainability"),
  bullet("Compare multiple ML models: Random Forest, XGBoost, LSTM, Isolation Forest"),
  bullet("Develop a real-time monitoring dashboard for maintenance personnel"),
  bullet("Deploy the system as a containerised microservice"),
  ...gap(1),
  h2("1.3 Expected Outcomes"),
  bullet("Failure detection with ≥90% recall and ≥85% precision"),
  bullet("Explanation reports highlighting top contributing sensor signals per alert"),
  bullet("End-to-end pipeline from raw CSV/stream ingestion to dashboard alert"),
  bullet("Reproducible experiment notebooks and REST API for model inference"),
  ...gap(1),
  infoBox("⚠  Scope Note",
    ["This project uses the publicly available MetroPT-3 dataset from UCI ML Repository.",
     "Dataset contains 1,516,948 rows across 15 analogue + 2 digital sensors at 1-second granularity.",
     "Target: binary label — 0 = Normal, 1 = Failure (air leakage / electro-valve fault)."],
    C.orangeBg, C.orange),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 2 — DATASET ═══
  h1("2. Dataset Description — MetroPT-3"),
  h2("2.1 Dataset Source"),
  p("UCI Machine Learning Repository — MetroPT-3 Dataset"),
  p("URL: https://archive.ics.uci.edu/dataset/791/metropt+3+dataset"),
  p("Original Paper: Veloso, B. et al. (2022). MetroPT: A Benchmark Dataset for Predictive Maintenance. Scientific Data, 9, 764."),
  ...gap(1),
  h2("2.2 Sensor Inventory"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2800, 2200, 2200, 2160],
    rows: [
      tableHeaderRow(["Sensor", "Type", "Unit", "Description"], [2800, 2200, 2200, 2160]),
      tableDataRow(["TP2", "Analogue", "bar", "Compressor pressure"], [2800, 2200, 2200, 2160], false),
      tableDataRow(["TP3", "Analogue", "bar", "Pneumatic panel pressure"], [2800, 2200, 2200, 2160], true),
      tableDataRow(["H1", "Analogue", "bar", "Downstream pressure"], [2800, 2200, 2200, 2160], false),
      tableDataRow(["DV_pressure", "Analogue", "bar", "Solenoid valve pressure"], [2800, 2200, 2200, 2160], true),
      tableDataRow(["Reservoirs", "Analogue", "bar", "Reservoir pressure"], [2800, 2200, 2200, 2160], false),
      tableDataRow(["Oil_temperature", "Analogue", "°C", "Compressor oil temperature"], [2800, 2200, 2200, 2160], true),
      tableDataRow(["Motor_current", "Analogue", "A", "Motor current draw"], [2800, 2200, 2200, 2160], false),
      tableDataRow(["COMP", "Digital", "0/1", "Compressor cycling state"], [2800, 2200, 2200, 2160], true),
      tableDataRow(["DV_eletric", "Digital", "0/1", "Electro-valve state"], [2800, 2200, 2200, 2160], false),
      tableDataRow(["Towers 1–4", "Analogue", "°C/bar", "Drying tower conditions"], [2800, 2200, 2200, 2160], true),
      tableDataRow(["LPS / PSCV", "Analogue", "bar", "Low pressure / control valve"], [2800, 2200, 2200, 2160], false),
    ]
  }),
  ...gap(1),
  h2("2.3 Class Distribution"),
  p("The dataset is highly imbalanced — critical for model design:"),
  bullet("Normal (class 0): ~1,490,000 rows (~98.2%)"),
  bullet("Failure (class 1): ~26,948 rows (~1.8%)"),
  p("Imbalance handling strategies covered in Chapter 7: SMOTE, class weighting, threshold tuning."),
  ...gap(1),
  h2("2.4 Downloading the Dataset"),
  code("# Option 1 — Direct download"),
  code("wget https://archive.ics.uci.edu/static/public/791/metropt+3+dataset.zip -O data/raw/metropt3.zip"),
  code("unzip data/raw/metropt3.zip -d data/raw/"),
  ...gap(1),
  code("# Option 2 — Python (ucimlrepo)"),
  code("pip install ucimlrepo"),
  code("from ucimlrepo import fetch_ucirepo"),
  code("metro = fetch_ucirepo(id=791)"),
  code("X, y = metro.data.features, metro.data.targets"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 3 — ARCHITECTURE ═══
  h1("3. System Architecture & Pipeline"),
  h2("3.1 High-Level Architecture"),
  infoBox("System Pipeline (End-to-End)",
    [
      "┌─────────────────────────────────────────────────────────────────┐",
      "│  DATA LAYER          PROCESSING LAYER        OUTPUT LAYER       │",
      "│                                                                  │",
      "│  MetroPT-3 CSV ───► Kafka Stream ──► Preprocessor              │",
      "│  Live APU Sensors       ▼                   ▼                   │",
      "│                   Spark Streaming ──► Feature Engineering       │",
      "│                         ▼                   ▼                   │",
      "│                   ML Inference ◄──── Trained Models             │",
      "│                   (RF/XGB/LSTM)      (sklearn/torch)            │",
      "│                         ▼                   ▼                   │",
      "│                   SHAP Explainer ──► Explanation Report         │",
      "│                         ▼                                        │",
      "│                   Streamlit Dashboard + REST API + Alerts       │",
      "└─────────────────────────────────────────────────────────────────┘",
    ],
    "1E293B", "94A3B8"),
  ...gap(1),
  h2("3.2 Repository Structure"),
  code("railway-xml-maintenance/"),
  code("├── data/"),
  code("│   ├── raw/           # Original MetroPT-3 CSV files"),
  code("│   ├── processed/     # Cleaned + feature-engineered data"),
  code("│   └── splits/        # Train / Val / Test splits"),
  code("├── notebooks/"),
  code("│   ├── 01_eda.ipynb"),
  code("│   ├── 02_feature_engineering.ipynb"),
  code("│   ├── 03_model_training.ipynb"),
  code("│   ├── 04_explainability.ipynb"),
  code("│   └── 05_evaluation.ipynb"),
  code("├── src/"),
  code("│   ├── preprocessing/"),
  code("│   ├── features/"),
  code("│   ├── models/"),
  code("│   ├── explainability/"),
  code("│   ├── streaming/"),
  code("│   └── api/"),
  code("├── dashboard/"),
  code("├── tests/"),
  code("├── docker/"),
  code("├── config/"),
  code("├── requirements.txt"),
  code("└── README.md"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 4 — ENVIRONMENT SETUP ═══
  h1("4. Environment Setup & Prerequisites"),
  h2("4.1 System Requirements"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2500, 6860],
    rows: [
      tableHeaderRow(["Component", "Minimum Requirement"], [2500, 6860]),
      tableDataRow(["OS", "Ubuntu 20.04 / macOS 12+ / Windows 11 (WSL2)"], [2500, 6860], false),
      tableDataRow(["CPU", "Intel i5 / AMD Ryzen 5 (8 cores recommended)"], [2500, 6860], true),
      tableDataRow(["RAM", "16 GB (32 GB recommended for LSTM training)"], [2500, 6860], false),
      tableDataRow(["Storage", "20 GB free (SSD recommended)"], [2500, 6860], true),
      tableDataRow(["GPU", "NVIDIA GPU with CUDA 11+ (optional, for LSTM)"], [2500, 6860], false),
      tableDataRow(["Python", "3.10 or 3.11"], [2500, 6860], true),
      tableDataRow(["Docker", "Docker Desktop 4.x"], [2500, 6860], false),
    ]
  }),
  ...gap(1),
  h2("4.2 Step-by-Step Environment Setup"),
  h3("Step 1 — Create Python Virtual Environment"),
  code("# Clone the repository"),
  code("git clone https://github.com/your-org/railway-xml-maintenance.git"),
  code("cd railway-xml-maintenance"),
  ...gap(1),
  code("# Create and activate virtual environment"),
  code("python -m venv venv"),
  code("source venv/bin/activate          # Linux/macOS"),
  code("venv\\Scripts\\activate           # Windows"),
  ...gap(1),
  code("# Upgrade pip"),
  code("pip install --upgrade pip setuptools wheel"),
  ...gap(1),
  h3("Step 2 — Install Core Dependencies"),
  code("# Install all requirements"),
  code("pip install -r requirements.txt"),
  ...gap(1),
  p("Contents of requirements.txt:"),
  code("# Core data science"),
  code("pandas==2.1.4"),
  code("numpy==1.26.2"),
  code("scipy==1.11.4"),
  code("scikit-learn==1.3.2"),
  ...gap(1),
  code("# ML Models"),
  code("xgboost==2.0.3"),
  code("lightgbm==4.1.0"),
  code("torch==2.1.2          # For LSTM"),
  code("torchvision==0.16.2"),
  ...gap(1),
  code("# Explainability"),
  code("shap==0.44.1"),
  code("lime==0.2.0.1"),
  code("eli5==0.13.0"),
  ...gap(1),
  code("# Data streaming"),
  code("kafka-python==2.0.2"),
  code("pyspark==3.5.0"),
  code("confluent-kafka==2.3.0"),
  ...gap(1),
  code("# Visualization & Dashboard"),
  code("matplotlib==3.8.2"),
  code("seaborn==0.13.0"),
  code("plotly==5.18.0"),
  code("streamlit==1.29.0"),
  ...gap(1),
  code("# API & utilities"),
  code("fastapi==0.109.0"),
  code("uvicorn==0.25.0"),
  code("mlflow==2.9.2"),
  code("imbalanced-learn==0.11.0"),
  ...gap(1),
  h3("Step 3 — Install Docker & Kafka"),
  code("# Verify Docker installation"),
  code("docker --version && docker-compose --version"),
  ...gap(1),
  code("# Start Kafka and Zookeeper via Docker Compose"),
  code("docker-compose -f docker/kafka-compose.yml up -d"),
  ...gap(1),
  code("# Verify Kafka is running"),
  code("docker ps | grep kafka"),
  ...gap(1),
  h3("Step 4 — Configure MLflow Tracking"),
  code("# Start MLflow UI (experiment tracking)"),
  code("mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db"),
  code("# Open browser: http://localhost:5000"),
  ...gap(1),
  infoBox("✅  Verification Checklist",
    ["□  Python 3.10+ active in virtual environment",
     "□  pip install -r requirements.txt completed without errors",
     "□  docker ps shows kafka and zookeeper containers running",
     "□  mlflow UI accessible at http://localhost:5000",
     "□  jupyter notebook launches successfully"],
    C.greenBg, C.green),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 5 — DATA PREPROCESSING ═══
  h1("5. Data Acquisition & Preprocessing"),
  h2("5.1 Loading the Dataset"),
  code("# src/preprocessing/loader.py"),
  code("import pandas as pd"),
  code("import numpy as np"),
  code("from pathlib import Path"),
  ...gap(1),
  code("def load_metropt(path: str = 'data/raw/MetroPT3(AirCompressor).csv') -> pd.DataFrame:"),
  code("    df = pd.read_csv(path, parse_dates=['timestamp'])"),
  code("    df = df.sort_values('timestamp').reset_index(drop=True)"),
  code("    print(f'Loaded {len(df):,} rows | {df.shape[1]} columns')"),
  code("    print(f'Date range: {df.timestamp.min()} → {df.timestamp.max()}')"),
  code("    return df"),
  ...gap(1),
  code("df = load_metropt()"),
  code("df.head()"),
  ...gap(1),
  h2("5.2 Data Quality Assessment"),
  code("# Check missing values"),
  code("missing = df.isnull().sum()"),
  code("print(missing[missing > 0])"),
  ...gap(1),
  code("# Check data types"),
  code("print(df.dtypes)"),
  ...gap(1),
  code("# Check for duplicates"),
  code("dups = df.duplicated(subset='timestamp').sum()"),
  code("print(f'Duplicate timestamps: {dups}')"),
  ...gap(1),
  code("# Statistical summary"),
  code("print(df.describe())"),
  ...gap(1),
  h2("5.3 Handling Missing Values"),
  code("# src/preprocessing/cleaner.py"),
  code("def clean_sensor_data(df: pd.DataFrame) -> pd.DataFrame:"),
  code("    # Forward fill for short gaps (< 5 seconds)"),
  code("    analogue_cols = ['TP2','TP3','H1','DV_pressure','Reservoirs',"),
  code("                     'Oil_temperature','Motor_current','COMP_pressure',"),
  code("                     'DV_eletric','Towers_1','Towers_2','Towers_3',"),
  code("                     'Towers_4','LPS','PSCV']"),
  ...gap(1),
  code("    df[analogue_cols] = df[analogue_cols].ffill(limit=5)"),
  ...gap(1),
  code("    # Interpolate remaining gaps"),
  code("    df[analogue_cols] = df[analogue_cols].interpolate(method='time', limit=30)"),
  ...gap(1),
  code("    # Drop rows still missing after interpolation"),
  code("    df = df.dropna(subset=analogue_cols)"),
  code("    print(f'After cleaning: {len(df):,} rows remaining')"),
  code("    return df"),
  ...gap(1),
  h2("5.4 Outlier Detection & Treatment"),
  code("from scipy import stats"),
  ...gap(1),
  code("def remove_outliers(df: pd.DataFrame, cols: list, z_thresh: float = 4.0):"),
  code("    '''Remove extreme physical impossibilities using Z-score'''"),
  code("    for col in cols:"),
  code("        z = np.abs(stats.zscore(df[col].dropna()))"),
  code("        outlier_mask = z > z_thresh"),
  code("        print(f'{col}: {outlier_mask.sum()} outliers found')"),
  code("        # Cap rather than drop (sensor spikes are real events)"),
  code("        upper = df[col].mean() + z_thresh * df[col].std()"),
  code("        lower = df[col].mean() - z_thresh * df[col].std()"),
  code("        df[col] = df[col].clip(lower, upper)"),
  code("    return df"),
  ...gap(1),
  h2("5.5 Train / Validation / Test Split"),
  p("Because the data is a time series, we use temporal splitting — never shuffle before splitting."),
  code("def temporal_split(df, train_ratio=0.70, val_ratio=0.15):"),
  code("    n = len(df)"),
  code("    train_end = int(n * train_ratio)"),
  code("    val_end   = int(n * (train_ratio + val_ratio))"),
  code("    train = df.iloc[:train_end]"),
  code("    val   = df.iloc[train_end:val_end]"),
  code("    test  = df.iloc[val_end:]"),
  code("    print(f'Train: {len(train):,}  Val: {len(val):,}  Test: {len(test):,}')"),
  code("    return train, val, test"),
  ...gap(1),
  infoBox("⚠  Time Series Splitting Rule",
    ["NEVER use sklearn's train_test_split with shuffle=True on time-series data.",
     "Future data leaking into training causes inflated performance metrics.",
     "Always use chronological (temporal) splits as shown above."],
    C.orangeBg, C.orange),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 6 — EDA ═══
  h1("6. Exploratory Data Analysis (EDA)"),
  h2("6.1 Class Distribution Analysis"),
  code("import matplotlib.pyplot as plt"),
  code("import seaborn as sns"),
  ...gap(1),
  code("# Class distribution"),
  code("label_counts = df['failure'].value_counts()"),
  code("print(f'Normal: {label_counts[0]:,}  ({label_counts[0]/len(df)*100:.1f}%)')"),
  code("print(f'Failure: {label_counts[1]:,} ({label_counts[1]/len(df)*100:.1f}%)')"),
  ...gap(1),
  code("# Plot"),
  code("fig, ax = plt.subplots(figsize=(8,4))"),
  code("ax.bar(['Normal','Failure'], label_counts.values, color=['#2563EB','#DC2626'])"),
  code("ax.set_title('Class Distribution (MetroPT-3 Dataset)')"),
  code("plt.savefig('reports/figures/class_distribution.png', dpi=150, bbox_inches='tight')"),
  ...gap(1),
  h2("6.2 Sensor Time-Series Visualisation"),
  code("# Plot key sensors over time"),
  code("fig, axes = plt.subplots(4, 1, figsize=(14, 12), sharex=True)"),
  code("sensors = ['TP2', 'TP3', 'Oil_temperature', 'Motor_current']"),
  code("colors  = ['#2563EB', '#0F766E', '#D97706', '#7C3AED']"),
  ...gap(1),
  code("for ax, sensor, color in zip(axes, sensors, colors):"),
  code("    ax.plot(df['timestamp'], df[sensor], color=color, lw=0.3, alpha=0.8)"),
  code("    # Highlight failure regions"),
  code("    failure_mask = df['failure'] == 1"),
  code("    ax.fill_between(df['timestamp'], df[sensor].min(), df[sensor].max(),"),
  code("                    where=failure_mask, alpha=0.3, color='red', label='Failure')"),
  code("    ax.set_ylabel(sensor, fontsize=10)"),
  code("plt.tight_layout()"),
  ...gap(1),
  h2("6.3 Correlation Analysis"),
  code("# Correlation heatmap for numeric sensors"),
  code("sensor_cols = ['TP2','TP3','H1','DV_pressure','Reservoirs',"),
  code("               'Oil_temperature','Motor_current','LPS','PSCV']"),
  code("corr = df[sensor_cols + ['failure']].corr()"),
  ...gap(1),
  code("plt.figure(figsize=(11,9))"),
  code("sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',"),
  code("            vmin=-1, vmax=1, center=0)"),
  code("plt.title('Sensor Correlation Matrix')"),
  code("plt.savefig('reports/figures/correlation_heatmap.png', dpi=150)"),
  ...gap(1),
  h2("6.4 Failure Event Analysis"),
  code("# Identify failure events (consecutive 1s = one event)"),
  code("from itertools import groupby"),
  ...gap(1),
  code("def get_failure_events(df):"),
  code("    events = []"),
  code("    failure_groups = []"),
  code("    in_failure = False"),
  code("    start = None"),
  code("    for idx, row in df.iterrows():"),
  code("        if row['failure'] == 1 and not in_failure:"),
  code("            start = row['timestamp']"),
  code("            in_failure = True"),
  code("        elif row['failure'] == 0 and in_failure:"),
  code("            events.append({'start': start, 'end': row['timestamp']})"),
  code("            in_failure = False"),
  code("    return events"),
  ...gap(1),
  code("events = get_failure_events(df)"),
  code("print(f'Total distinct failure events: {len(events)}')"),
  code("print(f'Avg event duration: {np.mean([(e[\"end\"]-e[\"start\"]).seconds for e in events]):.0f}s')"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 7 — FEATURE ENGINEERING ═══
  h1("7. Feature Engineering"),
  h2("7.1 Rolling Window Statistics"),
  p("Temporal features capture the dynamics of sensor signals — critical for early warning detection."),
  code("# src/features/rolling_features.py"),
  code("import pandas as pd, numpy as np"),
  ...gap(1),
  code("WINDOWS = [10, 30, 60, 300]   # seconds: 10s, 30s, 1min, 5min"),
  code("SENSORS = ['TP2','TP3','H1','DV_pressure','Oil_temperature','Motor_current']"),
  ...gap(1),
  code("def add_rolling_features(df: pd.DataFrame) -> pd.DataFrame:"),
  code("    df = df.set_index('timestamp').sort_index()"),
  code("    for sensor in SENSORS:"),
  code("        for w in WINDOWS:"),
  code("            roll = df[sensor].rolling(window=w, min_periods=1)"),
  code("            df[f'{sensor}_mean_{w}s'] = roll.mean()"),
  code("            df[f'{sensor}_std_{w}s']  = roll.std()"),
  code("            df[f'{sensor}_min_{w}s']  = roll.min()"),
  code("            df[f'{sensor}_max_{w}s']  = roll.max()"),
  code("            df[f'{sensor}_range_{w}s'] = roll.max() - roll.min()"),
  code("    return df.reset_index()"),
  ...gap(1),
  h2("7.2 Lag Features"),
  code("def add_lag_features(df, sensors, lags=[1, 5, 10, 30, 60]):"),
  code("    for sensor in sensors:"),
  code("        for lag in lags:"),
  code("            df[f'{sensor}_lag_{lag}'] = df[sensor].shift(lag)"),
  code("    return df"),
  ...gap(1),
  h2("7.3 Rate-of-Change Features"),
  code("def add_derivative_features(df, sensors):"),
  code("    '''First & second order derivatives (rate of change)'''"),
  code("    for sensor in sensors:"),
  code("        df[f'{sensor}_diff1'] = df[sensor].diff(1)       # 1st derivative"),
  code("        df[f'{sensor}_diff2'] = df[sensor].diff(1).diff(1)  # 2nd derivative"),
  code("    return df"),
  ...gap(1),
  h2("7.4 Domain-Specific Features"),
  code("def add_domain_features(df):"),
  code("    # Pressure differential (key indicator of valve issues)"),
  code("    df['pressure_diff_TP2_TP3'] = df['TP2'] - df['TP3']"),
  code("    df['pressure_diff_TP3_H1']  = df['TP3'] - df['H1']"),
  ...gap(1),
  code("    # Oil-to-motor heat index"),
  code("    df['heat_index'] = df['Oil_temperature'] * df['Motor_current']"),
  ...gap(1),
  code("    # Compressor cycle efficiency"),
  code("    df['cycle_efficiency'] = df['TP2'] / (df['Motor_current'] + 1e-6)"),
  ...gap(1),
  code("    # Time since last compressor cycle start"),
  code("    comp_starts = (df['COMP'].diff() == 1).cumsum()"),
  code("    df['time_since_cycle_start'] = df.groupby(comp_starts).cumcount()"),
  code("    return df"),
  ...gap(1),
  h2("7.5 Handling Class Imbalance with SMOTE"),
  code("from imblearn.over_sampling import SMOTE"),
  code("from imblearn.combine import SMOTETomek"),
  ...gap(1),
  code("def balance_classes(X_train, y_train, strategy='smote'):"),
  code("    if strategy == 'smote':"),
  code("        sampler = SMOTE(sampling_strategy=0.3, random_state=42)"),
  code("    elif strategy == 'smotetomek':"),
  code("        sampler = SMOTETomek(random_state=42)"),
  code("    X_res, y_res = sampler.fit_resample(X_train, y_train)"),
  code("    print(f'Before: {y_train.value_counts().to_dict()}')"),
  code("    print(f'After:  {pd.Series(y_res).value_counts().to_dict()}')"),
  code("    return X_res, y_res"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 8 — ML MODELS ═══
  h1("8. Machine Learning Models"),
  h2("8.1 Model Overview"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2400, 3160, 2000, 1800],
    rows: [
      tableHeaderRow(["Model", "Strength", "SHAP Support", "Best For"], [2400, 3160, 2000, 1800]),
      tableDataRow(["Random Forest", "Robust, low overfitting", "Yes (TreeExplainer)", "Baseline"], [2400, 3160, 2000, 1800], false),
      tableDataRow(["XGBoost", "High accuracy, gradient boosting", "Yes (TreeExplainer)", "Production"], [2400, 3160, 2000, 1800], true),
      tableDataRow(["LightGBM", "Fast training on large data", "Yes (TreeExplainer)", "Streaming"], [2400, 3160, 2000, 1800], false),
      tableDataRow(["Isolation Forest", "Unsupervised anomaly", "Partial", "Cold start"], [2400, 3160, 2000, 1800], true),
      tableDataRow(["LSTM (PyTorch)", "Temporal patterns", "Yes (GradientExplainer)", "Sequence"], [2400, 3160, 2000, 1800], false),
    ]
  }),
  ...gap(1),
  h2("8.2 Random Forest Classifier"),
  code("# src/models/random_forest.py"),
  code("from sklearn.ensemble import RandomForestClassifier"),
  code("from sklearn.model_selection import cross_val_score"),
  code("import mlflow, mlflow.sklearn"),
  ...gap(1),
  code("def train_random_forest(X_train, y_train, X_val, y_val):"),
  code("    with mlflow.start_run(run_name='RandomForest'):"),
  code("        params = {"),
  code("            'n_estimators': 300,"),
  code("            'max_depth': 15,"),
  code("            'min_samples_leaf': 5,"),
  code("            'class_weight': 'balanced',"),
  code("            'n_jobs': -1,"),
  code("            'random_state': 42"),
  code("        }"),
  code("        mlflow.log_params(params)"),
  code("        rf = RandomForestClassifier(**params)"),
  code("        rf.fit(X_train, y_train)"),
  ...gap(1),
  code("        # Evaluate"),
  code("        from sklearn.metrics import classification_report, roc_auc_score"),
  code("        y_pred = rf.predict(X_val)"),
  code("        y_prob = rf.predict_proba(X_val)[:, 1]"),
  code("        report = classification_report(y_val, y_pred, output_dict=True)"),
  code("        mlflow.log_metrics({'val_f1': report['1']['f1-score'],"),
  code("                            'val_recall': report['1']['recall'],"),
  code("                            'val_auc': roc_auc_score(y_val, y_prob)})"),
  code("        mlflow.sklearn.log_model(rf, 'random_forest_model')"),
  code("        return rf"),
  ...gap(1),
  h2("8.3 XGBoost Classifier"),
  code("import xgboost as xgb"),
  ...gap(1),
  code("def train_xgboost(X_train, y_train, X_val, y_val):"),
  code("    scale_pos_weight = (y_train==0).sum() / (y_train==1).sum()"),
  code("    params = {"),
  code("        'n_estimators': 500,"),
  code("        'max_depth': 8,"),
  code("        'learning_rate': 0.05,"),
  code("        'subsample': 0.8,"),
  code("        'colsample_bytree': 0.8,"),
  code("        'scale_pos_weight': scale_pos_weight,  # handles imbalance"),
  code("        'eval_metric': 'auc',"),
  code("        'early_stopping_rounds': 30,"),
  code("        'tree_method': 'gpu_hist',   # use 'hist' if no GPU"),
  code("        'random_state': 42"),
  code("    }"),
  code("    xgb_model = xgb.XGBClassifier(**params)"),
  code("    xgb_model.fit(X_train, y_train,"),
  code("                  eval_set=[(X_val, y_val)],"),
  code("                  verbose=50)"),
  code("    return xgb_model"),
  ...gap(1),
  h2("8.4 LSTM for Sequential Prediction"),
  code("# src/models/lstm_model.py"),
  code("import torch, torch.nn as nn"),
  ...gap(1),
  code("class APU_LSTM(nn.Module):"),
  code("    def __init__(self, input_size, hidden_size=128, num_layers=2, dropout=0.3):"),
  code("        super().__init__()"),
  code("        self.lstm = nn.LSTM(input_size, hidden_size,"),
  code("                            num_layers=num_layers,"),
  code("                            dropout=dropout, batch_first=True)"),
  code("        self.bn   = nn.BatchNorm1d(hidden_size)"),
  code("        self.fc   = nn.Sequential("),
  code("                        nn.Linear(hidden_size, 64),"),
  code("                        nn.ReLU(),"),
  code("                        nn.Dropout(0.3),"),
  code("                        nn.Linear(64, 1),"),
  code("                        nn.Sigmoid())"),
  code("    def forward(self, x):"),
  code("        out, _ = self.lstm(x)"),
  code("        out = self.bn(out[:, -1, :])   # last timestep"),
  code("        return self.fc(out)"),
  ...gap(1),
  code("# Training loop"),
  code("def train_lstm(model, train_loader, val_loader, epochs=30):"),
  code("    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)"),
  code("    criterion = nn.BCELoss()"),
  code("    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau("),
  code("                    optimizer, patience=3, factor=0.5)"),
  code("    device = 'cuda' if torch.cuda.is_available() else 'cpu'"),
  code("    model.to(device)"),
  code("    for epoch in range(epochs):"),
  code("        model.train()"),
  code("        for X_batch, y_batch in train_loader:"),
  code("            X_batch, y_batch = X_batch.to(device), y_batch.to(device)"),
  code("            optimizer.zero_grad()"),
  code("            loss = criterion(model(X_batch).squeeze(), y_batch.float())"),
  code("            loss.backward()"),
  code("            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)"),
  code("            optimizer.step()"),
  code("    return model"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 9 — EXPLAINABILITY ═══
  h1("9. Explainability with SHAP & LIME"),
  h2("9.1 Why Explainability Matters"),
  p("Railway maintenance engineers need to trust ML predictions. SHAP and LIME provide feature-level explanations for each prediction — answering: 'Why did the model flag this alarm?'"),
  ...gap(1),
  infoBox("XAI Methods Comparison",
    ["SHAP (Global + Local): Uses game-theoretic Shapley values. Consistent, theoretically sound. Best for tree models.",
     "LIME (Local): Approximates the model locally with an interpretable surrogate. Best for black-box local explanations.",
     "Feature Importance (Global): Aggregated variable importance. Fast but less informative per-prediction."],
    C.accent, C.blue),
  ...gap(1),
  h2("9.2 SHAP for Tree Models (XGBoost / Random Forest)"),
  code("# src/explainability/shap_explainer.py"),
  code("import shap"),
  code("import numpy as np, pandas as pd"),
  code("import matplotlib.pyplot as plt"),
  ...gap(1),
  code("class SHAPExplainer:"),
  code("    def __init__(self, model, X_train: pd.DataFrame):"),
  code("        self.explainer = shap.TreeExplainer(model)"),
  code("        self.feature_names = X_train.columns.tolist()"),
  ...gap(1),
  code("    def get_shap_values(self, X: pd.DataFrame) -> np.ndarray:"),
  code("        return self.explainer.shap_values(X)"),
  ...gap(1),
  code("    def plot_summary(self, X: pd.DataFrame, max_display: int = 20):"),
  code("        shap_vals = self.get_shap_values(X)"),
  code("        shap.summary_plot(shap_vals, X, max_display=max_display,"),
  code("                          show=False)"),
  code("        plt.savefig('reports/shap_summary.png', dpi=150, bbox_inches='tight')"),
  ...gap(1),
  code("    def explain_single_prediction(self, X_row: pd.DataFrame):"),
  code("        '''Returns top-5 contributing features for one prediction'''"),
  code("        sv = self.explainer.shap_values(X_row)[0]"),
  code("        contributions = pd.DataFrame({"),
  code("            'feature': self.feature_names,"),
  code("            'shap_value': sv,"),
  code("            'abs_shap': np.abs(sv)"),
  code("        }).sort_values('abs_shap', ascending=False).head(5)"),
  code("        return contributions"),
  ...gap(1),
  h2("9.3 SHAP Waterfall Plot for Individual Alerts"),
  code("def plot_waterfall(explainer, X_instance, idx=0):"),
  code("    '''Show how each feature drives one prediction toward failure'''"),
  code("    sv = explainer.explainer(X_instance)"),
  code("    shap.plots.waterfall(sv[idx], max_display=12, show=False)"),
  code("    plt.title(f'Alert Explanation — Sample #{idx}')"),
  code("    plt.savefig(f'reports/waterfall_{idx}.png', dpi=150)"),
  ...gap(1),
  h2("9.4 LIME for Local Explanations"),
  code("from lime import lime_tabular"),
  ...gap(1),
  code("class LIMEExplainer:"),
  code("    def __init__(self, X_train: np.ndarray, feature_names: list, mode='classification'):"),
  code("        self.lime_exp = lime_tabular.LimeTabularExplainer("),
  code("            training_data=X_train,"),
  code("            feature_names=feature_names,"),
  code("            class_names=['Normal', 'Failure'],"),
  code("            mode=mode,"),
  code("            random_state=42"),
  code("        )"),
  ...gap(1),
  code("    def explain(self, model, X_instance: np.ndarray, num_features=10):"),
  code("        exp = self.lime_exp.explain_instance("),
  code("            X_instance,"),
  code("            model.predict_proba,"),
  code("            num_features=num_features"),
  code("        )"),
  code("        return exp"),
  ...gap(1),
  code("    def show_explanation(self, exp):"),
  code("        exp.save_to_file('reports/lime_explanation.html')"),
  code("        print('\\nTop feature contributions:')"),
  code("        for feat, val in exp.as_list():"),
  code("            direction = '→ FAILURE' if val > 0 else '→ NORMAL'"),
  code("            print(f'  {feat:40s}  {val:+.4f}  {direction}')"),
  ...gap(1),
  h2("9.5 Generating Explanation Reports"),
  code("# Generate per-alert explanation report"),
  code("def generate_alert_report(model, shap_exp, lime_exp, X_alert, pred_prob):"),
  code("    report = {"),
  code("        'timestamp': str(X_alert.name),"),
  code("        'failure_probability': float(pred_prob),"),
  code("        'alert_level': 'HIGH' if pred_prob > 0.85 else 'MEDIUM',"),
  code("        'shap_top_features': shap_exp.explain_single_prediction(X_alert).to_dict(),"),
  code("        'lime_explanation': lime_exp.explain(model, X_alert.values).as_list()"),
  code("    }"),
  code("    return report"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 10 — EVALUATION ═══
  h1("10. Model Evaluation & Metrics"),
  h2("10.1 Why Standard Accuracy Fails Here"),
  p("With 98.2% normal instances, a model predicting 'always normal' achieves 98.2% accuracy — useless for maintenance. The right metrics for imbalanced binary classification are:"),
  ...gap(1),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2600, 4060, 2700],
    rows: [
      tableHeaderRow(["Metric", "Why It Matters", "Target"], [2600, 4060, 2700]),
      tableDataRow(["Recall (Sensitivity)", "Fraction of real failures caught — missing a failure is critical", "≥ 90%"], [2600, 4060, 2700], false),
      tableDataRow(["Precision", "Fraction of alerts that are real — too many false alarms waste resources", "≥ 80%"], [2600, 4060, 2700], true),
      tableDataRow(["F1 Score", "Harmonic mean of precision & recall — balanced measure", "≥ 85%"], [2600, 4060, 2700], false),
      tableDataRow(["ROC-AUC", "Model discrimination across all thresholds", "≥ 0.95"], [2600, 4060, 2700], true),
      tableDataRow(["PR-AUC", "Precision-Recall AUC — better than ROC for imbalanced data", "≥ 0.80"], [2600, 4060, 2700], false),
      tableDataRow(["Lead Time", "How far ahead of failure the model alerts", "≥ 15 min"], [2600, 4060, 2700], true),
    ]
  }),
  ...gap(1),
  h2("10.2 Full Evaluation Suite"),
  code("# src/evaluation/evaluator.py"),
  code("from sklearn.metrics import (classification_report, confusion_matrix,"),
  code("                             roc_auc_score, average_precision_score,"),
  code("                             RocCurveDisplay, PrecisionRecallDisplay)"),
  ...gap(1),
  code("def full_evaluation(model, X_test, y_test, threshold=0.5):"),
  code("    y_prob = model.predict_proba(X_test)[:, 1]"),
  code("    y_pred = (y_prob >= threshold).astype(int)"),
  ...gap(1),
  code("    print('=== Classification Report ===')"),
  code("    print(classification_report(y_test, y_pred, target_names=['Normal','Failure']))"),
  ...gap(1),
  code("    print(f'ROC-AUC:  {roc_auc_score(y_test, y_prob):.4f}')"),
  code("    print(f'PR-AUC:   {average_precision_score(y_test, y_prob):.4f}')"),
  ...gap(1),
  code("    # Confusion matrix"),
  code("    cm = confusion_matrix(y_test, y_pred)"),
  code("    tn, fp, fn, tp = cm.ravel()"),
  code("    print(f'TN={tn}  FP={fp}  FN={fn}  TP={tp}')"),
  ...gap(1),
  h2("10.3 Threshold Optimisation"),
  code("# Find optimal threshold maximising F1"),
  code("from sklearn.metrics import precision_recall_curve, f1_score"),
  ...gap(1),
  code("def optimise_threshold(y_true, y_prob):"),
  code("    precisions, recalls, thresholds = precision_recall_curve(y_true, y_prob)"),
  code("    f1_scores = 2*(precisions*recalls)/(precisions+recalls+1e-8)"),
  code("    best_idx = f1_scores.argmax()"),
  code("    best_thresh = thresholds[best_idx]"),
  code("    print(f'Optimal threshold: {best_thresh:.3f}')"),
  code("    print(f'F1 at optimal: {f1_scores[best_idx]:.4f}')"),
  code("    return best_thresh"),
  ...gap(1),
  h2("10.4 Lead Time Analysis"),
  code("def compute_lead_time(y_true, y_prob, timestamps, threshold=0.5):"),
  code("    '''Measure how early alerts precede actual failures'''"),
  code("    alerts = timestamps[y_prob >= threshold]"),
  code("    failures = timestamps[y_true == 1]"),
  code("    lead_times = []"),
  code("    for failure_time in failures.unique():"),
  code("        prior_alerts = alerts[alerts < failure_time]"),
  code("        if len(prior_alerts) > 0:"),
  code("            lead = (failure_time - prior_alerts.max()).seconds / 60"),
  code("            lead_times.append(lead)"),
  code("    print(f'Mean lead time: {np.mean(lead_times):.1f} minutes')"),
  code("    return lead_times"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 11 — STREAMING ═══
  h1("11. Real-Time Data Stream Processing"),
  h2("11.1 Kafka Setup & Topic Creation"),
  code("# docker/kafka-compose.yml"),
  code("version: '3.8'"),
  code("services:"),
  code("  zookeeper:"),
  code("    image: confluentinc/cp-zookeeper:7.4.0"),
  code("    environment:"),
  code("      ZOOKEEPER_CLIENT_PORT: 2181"),
  ...gap(1),
  code("  kafka:"),
  code("    image: confluentinc/cp-kafka:7.4.0"),
  code("    ports: ['9092:9092']"),
  code("    environment:"),
  code("      KAFKA_BROKER_ID: 1"),
  code("      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181"),
  code("      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092"),
  code("      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'"),
  ...gap(1),
  code("# Create APU sensor topic"),
  code("docker exec -it kafka kafka-topics --create \\"),
  code("  --bootstrap-server localhost:9092 \\"),
  code("  --topic apu-sensor-stream \\"),
  code("  --partitions 3 --replication-factor 1"),
  ...gap(1),
  h2("11.2 Sensor Data Producer (Simulates Live APU Feed)"),
  code("# src/streaming/producer.py"),
  code("from kafka import KafkaProducer"),
  code("import json, time, pandas as pd"),
  ...gap(1),
  code("class APUSensorProducer:"),
  code("    def __init__(self, bootstrap='localhost:9092', topic='apu-sensor-stream'):"),
  code("        self.producer = KafkaProducer("),
  code("            bootstrap_servers=bootstrap,"),
  code("            value_serializer=lambda v: json.dumps(v).encode('utf-8')"),
  code("        )"),
  code("        self.topic = topic"),
  ...gap(1),
  code("    def stream_csv(self, csv_path: str, speed_multiplier: float = 10.0):"),
  code("        '''Replay CSV at N× real-time speed'''"),
  code("        df = pd.read_csv(csv_path, parse_dates=['timestamp'])"),
  code("        for _, row in df.iterrows():"),
  code("            record = row.to_dict()"),
  code("            record['timestamp'] = str(record['timestamp'])"),
  code("            self.producer.send(self.topic, value=record)"),
  code("            time.sleep(1.0 / speed_multiplier)"),
  ...gap(1),
  h2("11.3 Real-Time Consumer & Inference"),
  code("# src/streaming/consumer.py"),
  code("from kafka import KafkaConsumer"),
  code("import json, joblib, numpy as np"),
  ...gap(1),
  code("class APUInferenceConsumer:"),
  code("    def __init__(self, model_path, scaler_path, feature_cols):"),
  code("        self.model   = joblib.load(model_path)"),
  code("        self.scaler  = joblib.load(scaler_path)"),
  code("        self.features = feature_cols"),
  code("        self.buffer   = []"),
  code("        self.consumer = KafkaConsumer("),
  code("            'apu-sensor-stream',"),
  code("            bootstrap_servers='localhost:9092',"),
  code("            value_deserializer=lambda v: json.loads(v.decode('utf-8')),"),
  code("            auto_offset_reset='latest'"),
  code("        )"),
  ...gap(1),
  code("    def run(self, alert_callback):"),
  code("        for msg in self.consumer:"),
  code("            record = msg.value"),
  code("            self.buffer.append(record)"),
  code("            if len(self.buffer) >= 60:  # 60-second window"),
  code("                X = self._build_features()"),
  code("                prob = self.model.predict_proba(X)[-1][1]"),
  code("                if prob >= 0.75:"),
  code("                    alert_callback({'timestamp': record['timestamp'],"),
  code("                                   'failure_prob': prob, 'record': record})"),
  code("                self.buffer = self.buffer[-30:]  # sliding window"),
  ...gap(1),
  h2("11.4 Alert Dispatcher"),
  code("def alert_callback(alert: dict):"),
  code("    level = 'CRITICAL' if alert['failure_prob'] > 0.9 else 'WARNING'"),
  code("    print(f'[{level}] {alert[\"timestamp\"]} — Failure probability: {alert[\"failure_prob\"]:.2%}')"),
  code("    # TODO: Send to Slack / email / SMS via notification service"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 12 — DASHBOARD ═══
  h1("12. Dashboard & Visualization"),
  h2("12.1 Streamlit Dashboard Overview"),
  p("The dashboard provides maintenance engineers with real-time sensor monitoring, ML prediction scores, and explainability insights in a single interface."),
  ...gap(1),
  h2("12.2 Main Dashboard Code"),
  code("# dashboard/app.py"),
  code("import streamlit as st"),
  code("import pandas as pd, numpy as np, plotly.express as px, plotly.graph_objects as go"),
  code("import shap, joblib, json"),
  code("from kafka import KafkaConsumer"),
  ...gap(1),
  code("st.set_page_config(page_title='APU Predictive Maintenance',"),
  code("                   layout='wide', page_icon='🚇')"),
  ...gap(1),
  code("# ─── Sidebar ───"),
  code("st.sidebar.title('⚙ Configuration')"),
  code("threshold = st.sidebar.slider('Alert Threshold', 0.5, 0.99, 0.75, 0.01)"),
  code("model_choice = st.sidebar.selectbox('Model', ['XGBoost','RandomForest','LSTM'])"),
  code("show_shap = st.sidebar.checkbox('Show SHAP Explanations', value=True)"),
  ...gap(1),
  code("# ─── KPIs ───"),
  code("col1, col2, col3, col4 = st.columns(4)"),
  code("col1.metric('System Status', '🟢 Normal', '+2h stable')"),
  code("col2.metric('Failure Probability', f'{prob:.1%}', delta_color='inverse')"),
  code("col3.metric('Active Alerts', '0', '-3 from yesterday')"),
  code("col4.metric('Next Maintenance', '14 days')"),
  ...gap(1),
  code("# ─── Sensor Trends ───"),
  code("st.subheader('📊 Live Sensor Readings')"),
  code("fig = px.line(live_df, x='timestamp', y=['TP2','TP3','Oil_temperature'],"),
  code("              title='Pressure & Temperature (Last 60 min)',"),
  code("              color_discrete_map={'TP2':'#2563EB','TP3':'#0F766E','Oil_temperature':'#D97706'})"),
  code("fig.add_hline(y=threshold_pressure, line_dash='dash', line_color='red')"),
  code("st.plotly_chart(fig, use_container_width=True)"),
  ...gap(1),
  code("# ─── SHAP Waterfall ───"),
  code("if show_shap and latest_alert:"),
  code("    st.subheader('🔍 Prediction Explanation (SHAP)')"),
  code("    shap_df = pd.DataFrame(latest_alert['shap_contributions'])"),
  code("    fig_shap = px.bar(shap_df.head(10), x='shap_value', y='feature',"),
  code("                      orientation='h', color='shap_value',"),
  code("                      color_continuous_scale='RdBu_r')"),
  code("    st.plotly_chart(fig_shap, use_container_width=True)"),
  ...gap(1),
  h2("12.3 Running the Dashboard"),
  code("# Launch dashboard"),
  code("streamlit run dashboard/app.py --server.port 8501"),
  code("# Open: http://localhost:8501"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 13 — DEPLOYMENT ═══
  h1("13. Deployment Guide"),
  h2("13.1 Dockerising the Application"),
  code("# docker/Dockerfile"),
  code("FROM python:3.11-slim"),
  code("WORKDIR /app"),
  code("COPY requirements.txt ."),
  code("RUN pip install --no-cache-dir -r requirements.txt"),
  code("COPY . ."),
  code("EXPOSE 8000 8501"),
  code("CMD [\"uvicorn\", \"src.api.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]"),
  ...gap(1),
  h2("13.2 Full Docker Compose Stack"),
  code("# docker/docker-compose.full.yml"),
  code("version: '3.8'"),
  code("services:"),
  code("  api:"),
  code("    build: ."),
  code("    ports: ['8000:8000']"),
  code("    volumes: ['./models:/app/models']"),
  code("    environment: [KAFKA_BOOTSTRAP=kafka:9092]"),
  code("    depends_on: [kafka, mlflow]"),
  ...gap(1),
  code("  dashboard:"),
  code("    build: ."),
  code("    command: streamlit run dashboard/app.py --server.port 8501"),
  code("    ports: ['8501:8501']"),
  ...gap(1),
  code("  mlflow:"),
  code("    image: ghcr.io/mlflow/mlflow:v2.9.2"),
  code("    ports: ['5000:5000']"),
  code("    volumes: ['./mlruns:/mlruns']"),
  ...gap(1),
  code("  kafka:"),
  code("    image: confluentinc/cp-kafka:7.4.0"),
  code("    ports: ['9092:9092']"),
  code("    environment:"),
  code("      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092"),
  ...gap(1),
  h2("13.3 REST API — FastAPI"),
  code("# src/api/main.py"),
  code("from fastapi import FastAPI"),
  code("from pydantic import BaseModel"),
  code("import joblib, numpy as np"),
  ...gap(1),
  code("app = FastAPI(title='Railway PdM API', version='1.0.0')"),
  code("model = joblib.load('models/xgboost_best.pkl')"),
  ...gap(1),
  code("class SensorReading(BaseModel):"),
  code("    TP2: float; TP3: float; H1: float"),
  code("    DV_pressure: float; Oil_temperature: float"),
  code("    Motor_current: float; Reservoirs: float"),
  ...gap(1),
  code("@app.post('/predict')"),
  code("async def predict_failure(reading: SensorReading):"),
  code("    X = np.array([[reading.TP2, reading.TP3, reading.H1,"),
  code("                   reading.DV_pressure, reading.Oil_temperature,"),
  code("                   reading.Motor_current, reading.Reservoirs]])"),
  code("    prob = model.predict_proba(X)[0][1]"),
  code("    return {'failure_probability': float(prob),"),
  code("            'alert': prob >= 0.75,"),
  code("            'alert_level': 'HIGH' if prob > 0.9 else 'MEDIUM' if prob > 0.75 else 'NONE'}"),
  ...gap(1),
  code("# Test the API"),
  code("curl -X POST http://localhost:8000/predict \\"),
  code("  -H 'Content-Type: application/json' \\"),
  code("  -d '{\"TP2\":5.5,\"TP3\":10.2,\"H1\":10.1,\"DV_pressure\":5.5,"),
  code("       \"Oil_temperature\":75.0,\"Motor_current\":8.2,\"Reservoirs\":8.4}'"),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 14 — TESTING ═══
  h1("14. Testing & Validation"),
  h2("14.1 Unit Tests"),
  code("# tests/test_preprocessing.py"),
  code("import pytest, pandas as pd, numpy as np"),
  code("from src.preprocessing.cleaner import clean_sensor_data"),
  ...gap(1),
  code("def test_missing_values_filled():"),
  code("    df = pd.DataFrame({'TP2': [5.0, np.nan, np.nan, 5.1], 'failure': [0,0,0,0]})"),
  code("    df['timestamp'] = pd.date_range('2024-01-01', periods=4, freq='1s')"),
  code("    result = clean_sensor_data(df)"),
  code("    assert result['TP2'].isnull().sum() == 0, 'Missing values should be filled'"),
  ...gap(1),
  code("def test_temporal_split_no_leakage():"),
  code("    from src.preprocessing.splitter import temporal_split"),
  code("    df = pd.DataFrame({'ts': pd.date_range('2024-01-01', periods=100, freq='1s'),"),
  code("                       'val': range(100)})"),
  code("    train, val, test = temporal_split(df)"),
  code("    assert train.index.max() < val.index.min(), 'Train must precede val'"),
  code("    assert val.index.max() < test.index.min(), 'Val must precede test'"),
  ...gap(1),
  h2("14.2 Model Performance Tests"),
  code("def test_recall_above_threshold():"),
  code("    '''Fail the build if recall drops below 0.88'''"),
  code("    from sklearn.metrics import recall_score"),
  code("    # Assumes model and test set are pre-loaded"),
  code("    y_pred = model.predict(X_test)"),
  code("    recall = recall_score(y_test, y_pred)"),
  code("    assert recall >= 0.88, f'Recall {recall:.3f} below threshold 0.88'"),
  ...gap(1),
  h2("14.3 Running the Full Test Suite"),
  code("# Run all tests with coverage"),
  code("pytest tests/ -v --cov=src --cov-report=html"),
  code("# Open coverage report: htmlcov/index.html"),
  ...gap(1),
  infoBox("📋  Acceptance Criteria (Must Pass Before Deployment)",
    ["✅  test_recall_above_threshold: recall ≥ 0.90",
     "✅  test_precision_above_threshold: precision ≥ 0.80",
     "✅  test_api_response_time: < 200ms per inference",
     "✅  test_kafka_consumer_no_lag: consumer lag < 100 messages",
     "✅  test_shap_explanations_generated: SHAP values non-null for all alerts",
     "✅  test_dashboard_loads: Streamlit app returns HTTP 200"],
    C.greenBg, C.green),
  new Paragraph({ children: [new PageBreak()] }),

  // ═══ CHAPTER 15 — TROUBLESHOOTING ═══
  h1("15. Troubleshooting & FAQs"),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [3200, 6160],
    rows: [
      tableHeaderRow(["Issue", "Solution"], [3200, 6160]),
      twoColRow("SMOTE memory error on full dataset", "Apply SMOTE only on training chunks. Use reservoir sampling or mini-batch SMOTE from imblearn."),
      twoColRow("SHAP TreeExplainer slow on large X_test", "Use shap.TreeExplainer with feature_perturbation='tree_path_dependent'. Sample 2000 rows for summary plot."),
      twoColRow("Kafka consumer offset lag", "Scale consumers: add more partitions. Check consumer group lag with kafka-consumer-groups.sh."),
      twoColRow("XGBoost GPU error: CUDA not found", "Set tree_method='hist' instead of 'gpu_hist'. Verify CUDA 11+ with nvidia-smi."),
      twoColRow("Streamlit dashboard freezing on live data", "Use st.empty() placeholder. Limit chart to last 500 points. Use @st.cache_data on model loading."),
      twoColRow("False alarm rate too high (low precision)", "Raise alert threshold to 0.80–0.85. Add a 'sustained alert' rule: only alert if prob > threshold for 3 consecutive windows."),
      twoColRow("LSTM not converging", "Normalise each sensor independently. Reduce learning rate to 1e-4. Check for NaN in gradients with torch.autograd.set_detect_anomaly(True)."),
      twoColRow("Docker OOM on training container", "Add shm_size: '2g' to docker-compose. Reduce LSTM batch_size to 64."),
    ]
  }),
  ...gap(2),
  // ═══ CHAPTER 16 — REFERENCES ═══
  h1("16. References & Resources"),
  h2("16.1 Dataset & Papers"),
  bullet("Veloso, B., et al. (2022). MetroPT: A Benchmark Dataset for Predictive Maintenance. Scientific Data, 9, 764."),
  bullet("Lundberg, S. & Lee, S.I. (2017). A Unified Approach to Interpreting Model Predictions. NeurIPS."),
  bullet("Ribeiro, M.T., Singh, S., Guestrin, C. (2016). 'Why Should I Trust You?': Explaining the Predictions of Any Classifier. KDD."),
  bullet("Chen, T. & Guestrin, C. (2016). XGBoost: A Scalable Tree Boosting System. KDD."),
  ...gap(1),
  h2("16.2 Useful Links"),
  bullet("MetroPT-3 Dataset: https://archive.ics.uci.edu/dataset/791/metropt+3+dataset"),
  bullet("SHAP Documentation: https://shap.readthedocs.io"),
  bullet("LIME GitHub: https://github.com/marcotcr/lime"),
  bullet("MLflow Docs: https://mlflow.org/docs/latest/index.html"),
  bullet("scikit-learn User Guide: https://scikit-learn.org/stable/user_guide.html"),
  bullet("Apache Kafka Quickstart: https://kafka.apache.org/quickstart"),
  bullet("Streamlit Docs: https://docs.streamlit.io"),
  ...gap(1),
  h2("16.3 Recommended Learning Path"),
  numbered("Complete Chapters 4–5 (setup + data loading) to verify your environment"),
  numbered("Run notebook 01_eda.ipynb to understand the data"),
  numbered("Run notebook 02_feature_engineering.ipynb — save processed data"),
  numbered("Run notebook 03_model_training.ipynb — compare RF, XGB, LSTM in MLflow"),
  numbered("Run notebook 04_explainability.ipynb — generate SHAP & LIME reports"),
  numbered("Launch dashboard: streamlit run dashboard/app.py"),
  numbered("Start Kafka producer + consumer for live simulation"),
  numbered("Containerise and deploy with Docker Compose"),
  ...gap(1),
  infoBox("🎓  Project Submission Checklist",
    ["□  Jupyter notebooks (01–05) executed end-to-end with outputs saved",
     "□  MLflow experiment showing ≥3 model runs with metrics",
     "□  SHAP summary plot + at least 5 waterfall plots for individual alerts",
     "□  LIME HTML report for at least 3 alert instances",
     "□  Streamlit dashboard screenshot / screen recording",
     "□  Docker Compose stack running all services",
     "□  pytest suite passing with ≥80% code coverage",
     "□  Final project report (IEEE format) documenting findings"],
    C.greenBg, C.green),

];

// ─── BUILD DOCUMENT ───────────────────────────────────────────────
const doc = new Document({
  numbering: {
    config: [
      {
        reference: "bullets",
        levels: [
          { level: 0, format: LevelFormat.BULLET, text: "•",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 540, hanging: 360 } } } },
          { level: 1, format: LevelFormat.BULLET, text: "◦",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 900, hanging: 360 } } } },
        ]
      },
      {
        reference: "numbers",
        levels: [
          { level: 0, format: LevelFormat.DECIMAL, text: "%1.",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 540, hanging: 360 } } } },
        ]
      }
    ]
  },
  styles: {
    default: { document: { run: { font: "Arial", size: 22, color: C.steel } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, font: "Arial", color: C.navy },
        paragraph: { spacing: { before: 360, after: 160 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: "Arial", color: C.blue },
        paragraph: { spacing: { before: 280, after: 120 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 22, bold: true, font: "Arial", color: C.teal },
        paragraph: { spacing: { before: 200, after: 80 }, outlineLevel: 2 } },
    ]
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 1440, right: 1260, bottom: 1440, left: 1260 }
      }
    },
    headers: {
      default: new Header({
        children: [
          new Paragraph({
            spacing: { before: 0, after: 100 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: C.navy, space: 4 } },
            children: [
              new TextRun({ text: "Explainable ML Framework for Railway Predictive Maintenance", font: "Arial", size: 18, color: C.navy, bold: true }),
              new TextRun({ text: "  |  MetroPT-3", font: "Arial", size: 18, color: C.steel }),
            ]
          })
        ]
      })
    },
    footers: {
      default: new Footer({
        children: [
          new Paragraph({
            spacing: { before: 100, after: 0 },
            border: { top: { style: BorderStyle.SINGLE, size: 4, color: C.silver, space: 4 } },
            tabStops: [{ type: TabStopType.RIGHT, position: 9360 }],
            children: [
              new TextRun({ text: "Confidential — Project Manual Guide", font: "Arial", size: 16, color: C.steel }),
              new TextRun({ text: "\tPage ", font: "Arial", size: 16, color: C.steel }),
              new SimpleField("PAGE", { font: "Arial", size: 16, color: C.navy, bold: true }),
            ]
          })
        ]
      })
    },
    children,
  }]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('C:\\Projects\\Feild_based_project\\Railway_PdM_Tutorial_Manual.docx', buf);
  console.log('SUCCESS — document written');
}).catch(err => {
  console.error('ERROR:', err);
  process.exit(1);
});